<template>
<section>
<div class="row">
    <header :class="{ 'scrolled__nav': scrollPostion }">
        <nav>
           <div class="col-lg-4 col-sm-4 ">
   <div class="logo">
                <img src="@/assets/PrivateeHolidays.svg" alt="logo">
            </div>
  </div>
  <div class="col-lg-8 col-sm-8 ">
  
            <ul v-if="!mobile" class="navigation">
                <li class="navigation__item">Home</li>
                <li class="navigation__item">Experience</li>
                <li class="navigation__item">Questions</li>
                <li class="navigation__item">Contacts</li>
            </ul>
            <div class="icon">
                <span @click="toggleNavBar()" v-if="mobile && !crossICon" :class="{ 'icon__active': mobileNav }">
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 640 640">
                        <title></title>
                        <g id="icomoon-ignore">
                        </g>
                        <path fill="#000" d="M0 96h640v64h-640v-64zM0 288h640v64h-640v-64zM0 480h640v64h-640v-64z">
                        </path>
                    </svg>
                </span>

                <span @click="toggleNavBar()" v-if="mobile && crossICon" :class="{ 'icon__active': mobileNav }">
                    <!-- Generated by IcoMoon.io -->
                    <!-- Generated by IcoMoon.io -->
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 640 640">
                        <title>cross</title>
                        <g id="icomoon-ignore">
                        </g>
                        <path
                            d="M507.331 411.33c-0.002-0.002-0.004-0.004-0.006-0.005l-155.322-155.325 155.322-155.325c0.002-0.002 0.004-0.003 0.006-0.005 1.672-1.673 2.881-3.627 3.656-5.708 2.123-5.688 0.912-12.341-3.662-16.915l-73.373-73.373c-4.574-4.573-11.225-5.783-16.914-3.66-2.080 0.775-4.035 1.984-5.709 3.655 0 0.002-0.002 0.003-0.004 0.005l-155.324 155.326-155.324-155.325c-0.002-0.002-0.003-0.003-0.005-0.005-1.673-1.671-3.627-2.88-5.707-3.655-5.69-2.124-12.341-0.913-16.915 3.66l-73.374 73.374c-4.574 4.574-5.784 11.226-3.661 16.914 0.776 2.080 1.985 4.036 3.656 5.708 0.002 0.001 0.003 0.003 0.005 0.005l155.325 155.324-155.325 155.326c-0.001 0.002-0.003 0.003-0.004 0.005-1.671 1.673-2.88 3.627-3.657 5.707-2.124 5.688-0.913 12.341 3.661 16.915l73.374 73.373c4.575 4.574 11.226 5.784 16.915 3.661 2.080-0.776 4.035-1.985 5.708-3.656 0.001-0.002 0.003-0.003 0.005-0.005l155.324-155.325 155.324 155.325c0.002 0.001 0.004 0.003 0.006 0.004 1.674 1.672 3.627 2.881 5.707 3.657 5.689 2.123 12.342 0.913 16.914-3.661l73.373-73.374c4.574-4.574 5.785-11.227 3.662-16.915-0.776-2.080-1.985-4.034-3.657-5.707z">
                        </path>
                    </svg>

                </span>



            </div>

            <div class="mobile__nav">
                <ul v-if="mobileNav" class="dropdown__navigation">
                    <li class="navigation__item">Home</li>
                    <li class="navigation__item">Experience</li>
                    <li class="navigation__item">Questions</li>
                    <li class="navigation__item">Contacts</li>
                </ul>
            </div>
  </div>
        </nav>
    </header>
  
</div>

</section>


    
</template>

<script>
export default {
    name: 'NavBar',
    data() {
        return {
            scrollPostion: null,
            mobile: null,
            mobileNav: null,
            windowwidth: null,
            crossICon: null
        };
    },
    created() {
        window.addEventListener('resize', this.checkWidth)
        this.checkWidth()
    },
    methods: {
        toggleNavBar() {

            this.mobileNav = !this.mobileNav;
            this.crossICon = !this.crossICon;
        },
        checkWidth() {
            this.windowwidth = window.innerWidth;
            if (this.windowwidth <= 750) {
                this.mobile = true
                return;
            }
            this.mobile = false
            this.mobileNav = false
            return;
        }
    }

}
</script>

<style lang="scss" scoped>
section{
    
    .row{
       
        header {
    background-color: white;
    z-index: 99;
    width: 100%;
    transition: 0.5s ease all;
    color: black;
    display: flex;
    flex-direction: row;
    justify-content: center;

    nav {
        position: relative;
        display: flex;
        flex-direction: row;
        width: 90%;
        padding: 12px 0px;
        margin: 0 auto;
        transition: 0.5s ease all;

        @media (min-width:1140px) {
            max-width: 1140px;
        }

        .navigation {
            display: flex;
            align-items: center;
            flex: 1;
            justify-content: flex-end;
        }

        ul,
        .navigation__item {
            font-weight: 500;
            color: black;
            text-decoration: none;
            list-style: none;
        }

        li {
            text-transform: uppercase;
            padding: 16px;
            margin-left: 16px;

        }

        .navigation__item {
            font-size: 14px;
            transition: 0.5s ease all;
            border-bottom: 1px solid transparent;
            padding-bottom: 4px;
            cursor: pointer;

            &:hover {
                border-bottom: 1px solid gray;
                color: gray;
                cursor: pointer;
            }
        }

        .logo {
            display: flex;
            align-items: center;
            cursor: pointer;

            img {
                width: 100%;
                height: 50px;
                transition: 0.5s ease all;

                @media (max-width:426px) {
                    width: 90%;
                    height: 30px;
                }
            }
        }

        .icon {
            display: flex;
            align-items: center;
            position: absolute;
            top: 0px;
            right: 8px;
            height: 100%;
            cursor: pointer;


        }

        .icon__active {
            transform: rotate(180deg);
            transition: 0.5s ease all;
        }

        .icon__not__active {
            transform: rotate(180deg);
            transition: 0.5s ease all;
        }

        .dropdown__navigation {
            display: flex;
            flex-direction: column;
            position: fixed;
            z-index: 100;
            width: 100%;
            max-width: 235px;
            height: 100%;
            background-color: white;
            top: 0;
            left: 0;

            li {
                margin-left: 0;

                .navigation__item {
                    color: white;
                }
            }
        }


    }
}
    }
}

</style>